# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_auto_20180324_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
