# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0004_auto_20180325_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='answer',
            field=models.TextField(),
        ),
    ]
