# Generated by Django 2.0.3 on 2018-04-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0006_auto_20180325_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='language',
            new_name='language_code',
        ),
    ]
