# Generated by Django 2.0.3 on 2018-04-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0007_auto_20180402_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='why_relevant',
            field=models.TextField(),
        ),
    ]
