# Generated by Django 2.0.3 on 2018-04-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0012_auto_20180413_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
