# Generated by Django 2.0.3 on 2018-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0014_auto_20180413_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
