# Generated by Django 2.0.3 on 2018-04-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0017_auto_20180415_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_new', models.BooleanField()),
                ('hits_count', models.IntegerField(default=0)),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiserver.Keyword')),
            ],
        ),
    ]
