# Generated by Django 2.0.3 on 2018-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0018_keywordhits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='keywordhits',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
