# Generated by Django 2.0.3 on 2018-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0019_auto_20180415_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='processed_status',
            field=models.CharField(default='success', max_length=50),
            preserve_default=False,
        ),
    ]
