# Generated by Django 2.0.3 on 2018-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0020_uploadeddocument_processed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_version',
            field=models.CharField(default='1.0.0', max_length=5),
            preserve_default=False,
        ),
    ]
