# Generated by Django 2.0.3 on 2018-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0021_event_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
