# Generated by Django 2.0.3 on 2018-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0022_auto_20180417_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
