# Generated by Django 2.0.3 on 2018-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0025_auto_20180418_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file_version',
            field=models.CharField(max_length=200),
        ),
    ]
